import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const downloadPDFSchedule = (selectedRows) => {
  if (selectedRows.length === 0) return;

  selectedRows.forEach((row) => {
    const doc = new jsPDF('l'); // ✅ Set PDF to Landscape
    const fileName = `${row.acadYear}_${row.semesterKey}.pdf`;
    doc.setFontSize(16);
    doc.text('Class Schedule Report', 148.5, 10, { align: 'center' }); // ✅ Centered horizontally in landscape
    doc.setFontSize(12);
    doc.text(`Academic Year: ${row.acadYear}`, 14, 20);
    doc.text(`Semester: ${row.semesterKey}`, 14, 26);
    let startY = 35;

    row.instructors.forEach((instructor) => {
      doc.setFontSize(11);
      doc.text(`Instructor: ${instructor.name}`, 14, startY);

      const courseData = instructor.courses.map((course) => [
        course.courseCode,
        course.courseDescription,
        course.curriculum,
        course.schedule.total_units,
        course.schedule.section || 'N/A',
        course.schedule.room || 'N/A',
        course.schedule.day || 'N/A',
        course.schedule.start_time || 'N/A',
        course.schedule.end_time || 'N/A',
      ]);

      autoTable(doc, {
        startY: startY + 5,
        head: [['Course Code', 'Description', 'Curriculum', 'Units', 'Section', 'Room', 'Day', 'Start Time', 'End Time']],
        body: courseData,
        theme: 'striped',
        styles: { fontSize: 9 },
        columnStyles: { 
          0: { cellWidth: 25 }, // Adjust column width for landscape
          1: { cellWidth: 60 },
          2: { cellWidth: 30 },
          3: { cellWidth: 15 },
          4: { cellWidth: 20 },
          5: { cellWidth: 20 },
          6: { cellWidth: 20 },
          7: { cellWidth: 20 },
          8: { cellWidth: 20 },
        },
      });

      startY = doc.lastAutoTable.finalY + 10;
    });

    // ✅ Add Footer
    doc.setFontSize(10);
    doc.text('Generated by Schedule Management System', 148.5, doc.internal.pageSize.height - 10, { align: 'center' });

    doc.save(fileName);
  });
};
